### ISSUE TITLE
DC-DC converter for running on USB-only power

### ISSUE THREAD

**Issue by jj1bdx** [jj1bdx/avrhwrng#5]
# MAX662A and power supply capacitors
- [Maxim MAX662A module from Akizuki Denshi](http://akizukidenshi.com/catalog/g/gI-01165/) was tested as a DC-DC converter for supplying the voltage of the noise diode circuits. It showed sufficient output of 12V with 40mV p-p ripple of ~6kHz (with the output current of ~1.2mA), converted from the USB DC 5V power supply.
- `v2rev1fix1`: Adding a filter capacitor of 10uF 25V ceramic to the power supply circuit of each of the noise diode unit (parallel to 100nF, after 100ohm resistor, before 47kohm resistor) reduced the 40mV p-p ripple voltage to a negligible level(unable to measure). Two 10uF ceramic caps needed for two units of circuits.
- The 10uF cap modification is applied to all existing four prototype boards as of 31-MAY-2016.
- The power consumption of the total circuits: 5V ~60mA (50~70mA).
## TODO
- [x] Stability test
- [x] Include the DC-DC converter circuit
- [x] Commit the DC-DC converter schematics to the repository
- [x] Add DC-DC converter circuit photos

**Comment by jj1bdx** [comment]
10uF filter caps included as v2rev1fix1 for the hardware. See https://github.com/jj1bdx/avrhwrng/commit/9eebbb0e6c47dd06371e971930c236741c130832

**Comment by jj1bdx** [comment]
All four prototypes are now equipped with the MAX662A DC-DC converter modules, stably running.

**Comment by jj1bdx** [comment]
Ceramic caps of the MAX662A modules generate small chirping noise, though this is not a malfunction, due to the mechanical vibration caused by inverse piezoelectric effect. Now I learn why a lot of wall warts are chirping!

**Comment by jj1bdx** [comment]
Committed DC-DC converter circuit schematics. See https://github.com/jj1bdx/avrhwrng/commit/bd103212111280deb5cf6b5a323b1dba1473dcfd and https://github.com/jj1bdx/avrhwrng/commit/bbaafeabf70c4c93d23f90d5e9ae0f4c58027b7d

**Comment by jj1bdx** [comment]
Short term stability test: 1~2 rndtest failures/day on FreeBSD with feedtrng. No observable difference from the non-DC-DC version. Stability test looks OK.

**Comment by jj1bdx** [comment]
All TODOs are completed. Issue closed.

**Comment by jj1bdx** [comment]
Photos for the DC-DC converter circuits are needed.

**Comment by jj1bdx** [comment]
Photos committed (see https://github.com/jj1bdx/avrhwrng/commit/6751774ed30a91e795d7c15323c54d753bb411ff).
Issue closed.
